---
# derived vars for xwiki

xwiki_catalina_opts: "-server -Dfile.encoding=utf-8 -Xmx{{ xwiki_tomcat_memory }} -Djava.security.egd=file:/dev/urandom -Dpdfbox.fontcache={{ xwiki_environment_permanent_directory }} -Djava.awt.headless=true -XX:+UseParallelGC -XX:MaxGCPauseMillis=100 -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true"

xwiki_postgres_jdbc_connection: "jdbc:postgresql://{{ xwiki_database_host }}:{{ xwiki_database_port }}/{{ xwiki_database }}"

xwiki_store_attachment_versioning_hint: "{{xwiki_store_attachment_hint}}"
xwiki_store_attachment_recyclebin_hint: "{{xwiki_store_attachment_hint}}"

postgresql_jdbc_driver_filename: "postgresql-{{ postgresql_jdbc_driver_version }}.jar"
postgresql_jdbc_driver_url: "https://jdbc.postgresql.org/download/{{ postgresql_jdbc_driver_filename }}"

xwiki_clojure_filename: "clojure-{{ xwiki_clojure_version }}.jar"
xwiki_clojure_download_url: "http://search.maven.org/remotecontent?filepath=org/clojure/clojure/{{ xwiki_clojure_version }}/{{ xwiki_clojure_filename }}"

xwiki_clojure_jsr223_download_url: "https://github.com/rastandy/clj-jsr223/releases/download/{{ xwiki_clojure_jsr223_version }}/{{ xwiki_clojure_jsr223_filename }}"

postfix_hostname: "{{ servername }}"
